title: Jesper Bergeskans
description: >-
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus venenatis 
  ex dapibus, scelerisque mi sit amet, tristique elit. Quisque interdum odio 
  ut elit commodo, ut gravida purus dapibus. Donec egestas, mauris non venenatis 
  accumsan, nulla lorem pellentesque nulla, viverra facilisis nibh sem sit amet sem.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://julmust.github.io/"
twitter_username: julmustbw
github_username:  julmust

# Build settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
